class ZCL_CM_OOALV_TOOLBAR_EXCLUDE definition
  public
  final
  create public .

public section.

  class-methods MT_TOOLBAR_EMPTY
    exporting
      !ET_EXCLUDE type UI_FUNCTIONS .
  class-methods MT_TOOLBAR_EXPORT
    exporting
      !ET_EXCLUDE type UI_FUNCTIONS .
protected section.
private section.
ENDCLASS.



CLASS ZCL_CM_OOALV_TOOLBAR_EXCLUDE IMPLEMENTATION.


method MT_TOOLBAR_EMPTY.


  DATA: LS_EXCLUDE TYPE UI_FUNC.

  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_EXCL_ALL.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.      "## ####
  LS_EXCLUDE =    CL_GUI_ALV_GRID=>MC_FC_DETAIL.                APPEND LS_EXCLUDE TO ET_EXCLUDE.            "####
  LS_EXCLUDE =   CL_GUI_ALV_GRID=>MC_FC_REFRESH.                APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Refresh

  LS_EXCLUDE =   CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.                APPEND LS_EXCLUDE TO ET_EXCLUDE.           "### ####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "### ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_PASTE.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "### ####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.       APPEND LS_EXCLUDE TO ET_EXCLUDE. "Paste new Row
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "####

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "# ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "# ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "# ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "# ##

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_GRAPH.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.             "###
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_INFO.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "Info

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_VIEW.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEWS.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.             "#####    '&VIEW'
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEW_CRYSTAL.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "######
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEW_EXCEL.              APPEND LS_EXCLUDE TO ET_EXCLUDE.        "####
  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_VIEW_GRID.                APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Grid##      '&VGRID'
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEW_LOTUS.              APPEND LS_EXCLUDE TO ET_EXCLUDE.        "

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SORT.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SORT_ASC.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "Sort ASC
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SORT_DSC.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "Sort DESC
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FIND.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.            "Find
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FIND_MORE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Find Next

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_FILTER.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FILTER.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Set ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_DELETE_FILTER.           APPEND LS_EXCLUDE TO ET_EXCLUDE.     "Del ##

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SUM.                     APPEND LS_EXCLUDE TO ET_EXCLUDE.               "Sum
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_MINIMUM.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Min
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_MAXIMUM.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Max
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_AVERAGE.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_AUF.                     APPEND LS_EXCLUDE TO ET_EXCLUDE.               "####&AUF
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SUBTOT.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.            "Sub Sum

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PRINT.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.             "###
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PRINT_BACK.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PRINT_PREV.              APPEND LS_EXCLUDE TO ET_EXCLUDE.

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_EXPORT.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.            "
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_DATA_SAVE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Export
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_WORD_PROCESSOR.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PC_FILE.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SEND.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "Send
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_TO_OFFICE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Office
  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_CALL_ABC.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.          "ABC##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_HTML.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "HTML

  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_LOAD_VARIANT.             APPEND LS_EXCLUDE TO ET_EXCLUDE.      "####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CURRENT_VARIANT.         APPEND LS_EXCLUDE TO ET_EXCLUDE.   "##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SAVE_VARIANT.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_MAINTAIN_VARIANT.        APPEND LS_EXCLUDE TO ET_EXCLUDE.  "Vari##

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_COL_OPTIMIZE.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "Optimize
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SEPARATOR.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "###
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SELECT_ALL.              APPEND LS_EXCLUDE TO ET_EXCLUDE.        "####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_DESELECT_ALL.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_COL_INVISIBLE.           APPEND LS_EXCLUDE TO ET_EXCLUDE.     "#####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FIX_COLUMNS.             APPEND LS_EXCLUDE TO ET_EXCLUDE.       "####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_UNFIX_COLUMNS.           APPEND LS_EXCLUDE TO ET_EXCLUDE.     "######
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_AVERAGE.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Average         '&AVERAGE'

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_F4.                      APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_HELP.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_ABC.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "               '&ABC'
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_CHAIN.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_BACK_CLASSIC.            APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_CRBATCH.            APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_CRWEB.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_LINEITEMS.          APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_MASTER_DATA.        APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_MORE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_REPORT.             APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_XINT.               APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_XXL.                APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPCRDATA.               APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPCRDESIG.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPCRTEMPL.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPMDB.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXTEND.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.            APPEND LS_EXCLUDE TO ET_EXCLUDE.

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_REPREP.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_TO_REP_TREE.             APPEND LS_EXCLUDE TO ET_EXCLUDE.
endmethod.


method MT_TOOLBAR_EXPORT.


  DATA: LS_EXCLUDE TYPE UI_FUNC.

*  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_EXCL_ALL.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.      "## ####
*  LS_EXCLUDE =    CL_GUI_ALV_GRID=>MC_FC_DETAIL.                APPEND LS_EXCLUDE TO ET_EXCLUDE.            "####
*  LS_EXCLUDE =   CL_GUI_ALV_GRID=>MC_FC_REFRESH.                APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Refresh

  LS_EXCLUDE =   CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.                APPEND LS_EXCLUDE TO ET_EXCLUDE.           "### ####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "### ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_PASTE.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "### ####
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.       APPEND LS_EXCLUDE TO ET_EXCLUDE. "Paste new Row
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "####

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "# ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "# ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "# ##
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "# ##

  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_GRAPH.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.             "###
  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_INFO.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "Info
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_VIEW.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEWS.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.             "#####    '&VIEW'
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEW_CRYSTAL.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "######
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEW_EXCEL.              APPEND LS_EXCLUDE TO ET_EXCLUDE.        "####
*  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_VIEW_GRID.                APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Grid##      '&VGRID'
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_VIEW_LOTUS.              APPEND LS_EXCLUDE TO ET_EXCLUDE.        "
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SORT.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SORT_ASC.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "Sort ASC
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SORT_DSC.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "Sort DESC
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FIND.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.            "Find
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FIND_MORE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Find Next
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_FILTER.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FILTER.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Set ##
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_DELETE_FILTER.           APPEND LS_EXCLUDE TO ET_EXCLUDE.     "Del ##

*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SUM.                     APPEND LS_EXCLUDE TO ET_EXCLUDE.               "Sum
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_MINIMUM.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Min
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_MAXIMUM.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Max
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_AVERAGE.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "##
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_AUF.                     APPEND LS_EXCLUDE TO ET_EXCLUDE.               "####&AUF
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SUBTOT.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.            "Sub Sum
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PRINT.                   APPEND LS_EXCLUDE TO ET_EXCLUDE.             "###
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PRINT_BACK.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PRINT_PREV.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_MB_EXPORT.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.            "
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_DATA_SAVE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Export
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_WORD_PROCESSOR.          APPEND LS_EXCLUDE TO ET_EXCLUDE.    "##
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_PC_FILE.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "####
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SEND.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "Send
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_TO_OFFICE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "Office
*  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_CALL_ABC.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.          "ABC##
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_HTML.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.              "HTML
*
*  LS_EXCLUDE = CL_GUI_ALV_GRID=>MC_FC_LOAD_VARIANT.             APPEND LS_EXCLUDE TO ET_EXCLUDE.      "####
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CURRENT_VARIANT.         APPEND LS_EXCLUDE TO ET_EXCLUDE.   "##
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SAVE_VARIANT.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "##
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_MAINTAIN_VARIANT.        APPEND LS_EXCLUDE TO ET_EXCLUDE.  "Vari##
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_COL_OPTIMIZE.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "Optimize
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SEPARATOR.               APPEND LS_EXCLUDE TO ET_EXCLUDE.         "###
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_SELECT_ALL.              APPEND LS_EXCLUDE TO ET_EXCLUDE.        "####
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_DESELECT_ALL.            APPEND LS_EXCLUDE TO ET_EXCLUDE.      "####
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_COL_INVISIBLE.           APPEND LS_EXCLUDE TO ET_EXCLUDE.     "#####
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_FIX_COLUMNS.             APPEND LS_EXCLUDE TO ET_EXCLUDE.       "####
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_UNFIX_COLUMNS.           APPEND LS_EXCLUDE TO ET_EXCLUDE.     "######
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_AVERAGE.                 APPEND LS_EXCLUDE TO ET_EXCLUDE.           "Average         '&AVERAGE'

*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_F4.                      APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_HELP.                    APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_ABC.                APPEND LS_EXCLUDE TO ET_EXCLUDE.          "               '&ABC'
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_CHAIN.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_BACK_CLASSIC.            APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_CRBATCH.            APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_CRWEB.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_LINEITEMS.          APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_MASTER_DATA.        APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_MORE.               APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_REPORT.             APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_XINT.               APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_CALL_XXL.                APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPCRDATA.               APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPCRDESIG.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPCRTEMPL.              APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXPMDB.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_EXTEND.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_LOC_MOVE_ROW.            APPEND LS_EXCLUDE TO ET_EXCLUDE.
*
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_REPREP.                  APPEND LS_EXCLUDE TO ET_EXCLUDE.
*  LS_EXCLUDE =  CL_GUI_ALV_GRID=>MC_FC_TO_REP_TREE.             APPEND LS_EXCLUDE TO ET_EXCLUDE.
endmethod.
ENDCLASS.
