FUNCTION ZCM_EXCEL_DISPLAY.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_CLSNAM) TYPE  BDS_CLSNAM DEFAULT 'PICTURES'
*"     VALUE(I_CLSTYP) TYPE  BDS_CLSTYP DEFAULT 'OT'
*"     VALUE(I_TYPEID) TYPE  BDS_TYPEID
*"     VALUE(I_FILENA) TYPE  BDS_FILENA
*"     REFERENCE(I_CALLBACK_PROGRAM) TYPE  SY-REPID DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_FILL_DATA) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_PF_STATUS_SET) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_USER_COMMAND) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_NEXT) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_TITLE) TYPE  DTITLE DEFAULT 'SAP'
*"     REFERENCE(IS_OPTIONS) TYPE  ZCM_DOIOPTS OPTIONAL
*"  EXCEPTIONS
*"      PROGRAM_ERROR
*"----------------------------------------------------------------------





ENDFUNCTION.
