FUNCTION-POOL ZFGCM02 MESSAGE-ID ZCM001PM.                      "MESSAGE-ID ..
DATA: GT_GLOBE_RSPARAMS TYPE TABLE OF RSPARAMS.
DATA: GS_GLOBE_BKPARA TYPE ZCM_IN_CALL_BGP.
DATA: GV_GLOBE_BGP_RECALL TYPE CHAR1.
DATA: GO_LOG_UPDATE TYPE REF TO ZCL_CM_CUSTOM_LOG .
DATA: GV_LOG_UUID TYPE SYSUUID_C.
