FUNCTION ZCM_EXCEL2INTERNELTAB.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IT_FIELDCAT_LVC) TYPE  LVC_T_FCAT OPTIONAL
*"     REFERENCE(I_STRUCTURE_NAME) TYPE  DD02L-TABNAME OPTIONAL
*"     REFERENCE(IS_LAYOUT_LVC) TYPE  LVC_S_LAYO
*"     REFERENCE(NO_HEADER) TYPE  CHAR1 DEFAULT ''
*"     REFERENCE(ACT_VAR) TYPE  CHAR1 DEFAULT 'X'
*"     REFERENCE(IS_VARIANT) LIKE  DISVARIANT STRUCTURE  DISVARIANT
*"  TABLES
*"      T_OUTTAB
*"----------------------------------------------------------------------

 DATA: LV_LENS TYPE SY-TABIX.

  CHECK T_OUTTAB[] IS NOT INITIAL.

  DESCRIBE TABLE T_OUTTAB[] LINES LV_LENS.
  IF LV_LENS > 1000.
    MESSAGE E005(ZCM001PM).
  ENDIF.
*  CHECK GV_ACT_VAR IS NOT INITIAL AND IS_VARIANT IS INITIAL.

  ASSIGN T_OUTTAB[] TO <GLB_TABLE_ITEM>.
  GV_STRUCTURE_NAME = I_STRUCTURE_NAME.
  GV_ACT_VAR = ACT_VAR.
  GV_NO_HEADER = NO_HEADER.
  GT_FCAT_OLD[] = IT_FIELDCAT_LVC[].

  PERFORM FRM_CHANGE_STRUCTURE_FACT.
*  if ACT_VAR = 'X' get new globe fcat from Variant Layout
  PERFORM FRM_GET_GLOBE_FCAT USING IS_LAYOUT_LVC IS_VARIANT.

*  use sap structure produce excel header
  PERFORM FRM_CREAT_DYNAMIC_EXCEL_HEADER.
  PERFORM FRM_CREAT_DYNAMIC_ITEM.

  CALL FUNCTION 'ZCM_EXCEL_DOWNLOAD'
    EXPORTING
      I_CLSNAM             = 'PICTURES'
      I_CLSTYP             = 'OT'
      I_TYPEID             = 'ZBDC'
      I_FILENA             = 'DOWNLOAD_TEMPLATE.xls'
      I_TITLE              = 'DOWNLOAD_TEMPLATE'
      I_CALLBACK_PROGRAM   = SY-REPID
      I_CALLBACK_FILL_DATA = 'FRM_FILL_EXCEL_OUTTAB'
*      I_CALLBACK_NEXT      = 'FRM_PRINT_NEXT'
*      IS_OPTIONS           = LS_OPTIONS
    EXCEPTIONS
      PROGRAM_ERROR        = 1
      OTHERS               = 2.




ENDFUNCTION.
