FUNCTION ZCM_EXCEL_DOWNLOAD.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_CLSNAM) TYPE  BDS_CLSNAM DEFAULT 'PICTURES'
*"     VALUE(I_CLSTYP) TYPE  BDS_CLSTYP DEFAULT 'OT'
*"     VALUE(I_TYPEID) TYPE  BDS_TYPEID
*"     VALUE(I_FILENA) TYPE  BDS_FILENA
*"     REFERENCE(I_CALLBACK_PROGRAM) TYPE  SY-REPID DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_FILL_DATA) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_PF_STATUS_SET) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_USER_COMMAND) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_NEXT) TYPE  FORMNAME DEFAULT SPACE
*"     REFERENCE(I_TITLE) TYPE  DTITLE DEFAULT 'SAP'
*"     REFERENCE(IS_OPTIONS) TYPE  ZCM_DOIOPTS OPTIONAL
*"  EXCEPTIONS
*"      PROGRAM_ERROR
*"----------------------------------------------------------------------


* DOI Support 检查
  PERFORM FRM_DOI_CHECK.

* Check callback parameters
  IF I_CALLBACK_PROGRAM IS INITIAL AND
    ( NOT I_CALLBACK_FILL_DATA     IS INITIAL OR
      NOT I_CALLBACK_USER_COMMAND  IS INITIAL OR
      NOT I_CALLBACK_PF_STATUS_SET IS INITIAL ).
    MESSAGE A529(0K) RAISING PROGRAM_ERROR.
  ENDIF.

* Initialize data
  PERFORM FRM_INITIALIZE_DATA.

  G_CLSNAM = I_CLSNAM. "Class name
  G_CLSTYP = I_CLSTYP. "Class type
  G_TYPEID = I_TYPEID. "Object key
  G_FILENA = I_FILENA. "File name

* Variables for callback
  G_CALLBACK_PROGRAM       = I_CALLBACK_PROGRAM       .
  G_CALLBACK_FILL_DATA     = I_CALLBACK_FILL_DATA     .
  G_CALLBACK_PF_STATUS_SET = I_CALLBACK_PF_STATUS_SET .
  G_CALLBACK_USER_COMMAND  = I_CALLBACK_USER_COMMAND  .
  G_CALLBACK_NEXT          = I_CALLBACK_NEXT          .

* Sceen title
  G_TITLE = I_TITLE.
* Options
  IF IS_OPTIONS IS SUPPLIED.
    GS_OPTIONS = IS_OPTIONS.
  ENDIF.


  IF GF_INITIALIZED IS INITIAL.
    GF_INITIALIZED = 'X'.
  ELSE.
    RETURN.
  ENDIF.
* Document URL
  DATA: L_URL TYPE BDS_URI.

* Fetch Document URL
  PERFORM FRM_GET_BDS_URL USING G_CLSNAM
                                G_CLSTYP
                                G_TYPEID
                                G_FILENA
                       CHANGING L_URL.

* 创建基本对象
  PERFORM FRM_CREATE_DOI_OBJECTS USING    L_URL
                                          'X'
                                          GS_OPTIONS-INPLACE_SHOW_TOOLBARS
                                 CHANGING GR_CONTROL
                                          GR_PROXY
                                          GR_SPREADSHEET.

* Callback
  IF NOT G_CALLBACK_FILL_DATA IS INITIAL.
    PERFORM (G_CALLBACK_FILL_DATA)
            IN PROGRAM (G_CALLBACK_PROGRAM)
            USING GR_CONTROL
                  GR_PROXY
                  GR_SPREADSHEET
            IF FOUND.
  ENDIF.


  DATA: LV_TMP_VALUE TYPE CHAR20.

*  FREE MEMORY ID 'Z_TMP_ZDOI_EXCEL_DOWNLOAD'.
  IMPORT LV_TMP_VALUE FROM MEMORY ID 'Z_MID_DOWNLOAD'.

  IF LV_TMP_VALUE IS NOT INITIAL.
    G_FILENA = LV_TMP_VALUE.
  ENDIF.


  PERFORM FRM_SAVE_COPY_AS USING GR_PROXY G_FILENA.
  PERFORM FRM_LEAVE.




ENDFUNCTION.
