FUNCTION-POOL ZFGCM04 MESSAGE-ID ZCM001PM.                      "MESSAGE-ID ..

TYPE-POOLS: SLIS.

*&---------------------------------------------------------------------*
*    Data Description
*&---------------------------------------------------------------------*

* Variables for DOI
DATA: GR_CONTROL TYPE REF TO I_OI_CONTAINER_CONTROL "Container Control
    , GR_PROXY   TYPE REF TO I_OI_DOCUMENT_PROXY    "General Document
    , GR_SPREADSHEET TYPE REF TO I_OI_SPREADSHEET   "Spreadsheet
    , T_OUTTAB

    .
DATA: OK_CODE TYPE SYUCOMM.
DATA: GF_INITIALIZED TYPE FLAG.

* 以下4个值为Tcode:OAOR里面新建模板文件的参数
DATA: G_CLSNAM TYPE BDS_CLSNAM . "Class name
DATA: G_CLSTYP TYPE BDS_CLSTYP . "Class type
DATA: G_TYPEID TYPE BDS_TYPEID . "Object key
DATA: G_FILENA TYPE BDS_FILENA . "File name

* Variables for callback
DATA: G_CALLBACK_PROGRAM       TYPE SY-REPID,
      G_CALLBACK_FILL_DATA     TYPE FORMNAME,
      G_CALLBACK_FILL_DATA_OUT TYPE FORMNAME,
      G_CALLBACK_PF_STATUS_SET TYPE FORMNAME,
      G_CALLBACK_USER_COMMAND  TYPE FORMNAME,
      G_CALLBACK_CHECK_FIELD   TYPE FORMNAME,
      G_CALLBACK_NEXT          TYPE FORMNAME.

* Screen title
DATA: G_TITLE TYPE DTITLE.

* Options
DATA: GS_OPTIONS TYPE ZCM_DOIOPTS.
DATA: GS_UPOPTIONS TYPE ZCM_DOIUPOPTS.
DATA: GT_SOLIX TYPE TABLE OF SOLIX.

FIELD-SYMBOLS: <DYN_UPLOAD_TABLE> TYPE TABLE.
DATA:GT_FCAT TYPE LVC_T_FCAT.
DATA:GT_FCAT_OLD TYPE LVC_T_FCAT.
DATA: GV_EXCEL_COLUMN TYPE I.
FIELD-SYMBOLS: <DYN_TABLE_HEADER> TYPE TABLE.
FIELD-SYMBOLS: <DYN_TABLE_ITEM> TYPE TABLE.
FIELD-SYMBOLS: <GLB_TABLE_ITEM> TYPE ANY TABLE.
DATA: GV_STRUCTURE_NAME TYPE DD02L-TABNAME.
DATA: GV_NO_HEADER TYPE CHAR1.
DATA: GV_ACT_VAR TYPE CHAR1.
DATA: GV_ATTACHMENTS_SAVE TYPE CHAR1.
*DATA: GO_LOG_UPDATE TYPE REF TO ZCL_CM_CUSTOM_LOG ..                      "MESSAGE-ID ..

* INCLUDE LZFGCM04D...                       " Local class definition
