FUNCTION ZCM_CALL_BDC.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(NAME) TYPE  APQI-GROUPID
*"     VALUE(TCODE) TYPE  TCODE OPTIONAL
*"     VALUE(CTU_PARAMS) TYPE  CTU_PARAMS OPTIONAL
*"     VALUE(LOG_WADATA) TYPE  SYCHAR512 OPTIONAL
*"  EXPORTING
*"     VALUE(ICON) TYPE  ICON_D
*"     VALUE(MSG) TYPE  BAPI_MSG
*"     VALUE(MTYPE) TYPE  BAPI_MTYPE
*"  TABLES
*"      BDC_TAB STRUCTURE  BDCDATA
*"      RETURN STRUCTURE  BAPIRET2 OPTIONAL
*"----------------------------------------------------------------------



  DATA: LS_RETURN TYPE BAPIRET2.

  PERFORM FRM_CLEAR_GLOBE_BDC_VAR.

  GV_GLOBE_CTU_PARAMS = CTU_PARAMS.
  GV_GLOBE_BDC_NAME = NAME.
  GV_GLOBE_BDC_TCODE = TCODE.
  GV_GLOBE_LOG_WADATA = LOG_WADATA.
  GT_GLOBE_BDC_TAB[] = BDC_TAB[].


  PERFORM FRM_CHECK_CTU_PARAMS.

  PERFORM FRM_CALL_BDC.

  LOOP AT GT_GLOBE_BDC_RETURN INTO LS_RETURN WHERE TYPE CA 'EA'.

    IF LS_RETURN-MESSAGE IS NOT INITIAL.
      MESSAGE ID     LS_RETURN-ID
              TYPE   LS_RETURN-TYPE
              NUMBER LS_RETURN-NUMBER
              INTO   LS_RETURN-MESSAGE
              WITH   LS_RETURN-MESSAGE_V1
                     LS_RETURN-MESSAGE_V2
                     LS_RETURN-MESSAGE_V3
                     LS_RETURN-MESSAGE_V4.
    ENDIF.
    CONCATENATE MSG LS_RETURN-MESSAGE INTO MSG.

  ENDLOOP.
* 如果有错误,但是消息是空的,报未知错误
  IF SY-SUBRC EQ 0 .
    MTYPE = 'E'.
    ICON = '@0A@'.
  ELSE."成功
    MTYPE = 'S'.
    LOOP AT GT_GLOBE_BDC_RETURN INTO LS_RETURN.

      IF LS_RETURN-MESSAGE IS NOT INITIAL.
        MESSAGE ID     LS_RETURN-ID
                TYPE   LS_RETURN-TYPE
                NUMBER LS_RETURN-NUMBER
                INTO   LS_RETURN-MESSAGE
                WITH   LS_RETURN-MESSAGE_V1
                       LS_RETURN-MESSAGE_V2
                       LS_RETURN-MESSAGE_V3
                       LS_RETURN-MESSAGE_V4.
      ENDIF.
      CONCATENATE MSG LS_RETURN-MESSAGE INTO MSG.
      ICON = '@08@'.
    ENDLOOP.

  ENDIF.

  CREATE OBJECT GO_LOG_UPDATE.

  RETURN[] = GT_GLOBE_BDC_RETURN[].


ENDFUNCTION.
