FUNCTION-POOL ZFGCM01 MESSAGE-ID MS.                      "MESSAGE-ID ..

* INCLUDE LZFGCM01D...                       " Local class definition

TABLES:D0100,BDC_RECORD.

DATA: GV_GLOBE_CTU_PARAMS TYPE CTU_PARAMS.
DATA: GV_GLOBE_BDC_NAME TYPE APQI-GROUPID.
DATA: GV_GLOBE_BDC_TCODE TYPE TCODE.
DATA: GV_GLOBE_BDC_EXCEL_COLUMN TYPE I.
DATA: GV_GLOBE_LOG_WADATA TYPE SYCHAR512.

DATA: GT_GLOBE_BDC_TAB TYPE BDCDATA_TAB.
DATA: GT_GLOBE_BDC_TAB_FIELD TYPE BDCDATA_TAB.
DATA: GT_GLOBE_BDC_FCAT TYPE LVC_T_FCAT."是Table Type
DATA: GT_GLOBE_BDC_RETURN TYPE TABLE OF BAPIRET2.
DATA: GO_LOG_UPDATE TYPE REF TO ZCL_CM_CUSTOM_LOG .
FIELD-SYMBOLS: <DYN_GLOBE_TABLE> TYPE TABLE.
